### ISSUE TITLE
MainDB: Database is corrupted

### ISSUE THREAD

**Issue by outlogic** [plotn/coolreader#109]
При каждом запуске возникает сообщение
MainDB: Database is corrupted
MainDB: Performed rename

**Comment by plotn** [comment]
Необходимо собрать логи работы приложения, без этого понять почти невозможно

**Comment by outlogic** [comment]
У меня подозрение, что проблема возникает, когда имя файла слишком длинное.
Попробовал несколько книг, вот на этой рушится база https://drive.google.com/open?id=1uiccEVLnKvufEM-wWutT0sNXfewm-0uG Можете попробовать у себя?

У меня подобное было, когда КулРидер вообще перестал запускаться после экспорта закладок. Когда удалил файлы с книгами и закладками, проблема исчезла.

**Comment by plotn** [comment]
С книгой проблем нет

**Comment by plotn** [comment]
Починено
