### ISSUE TITLE
Работа со сносками

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#11]
1. Рассмотреть возможность рисования сносок снизу, когда страница неполная.
2. Рассмотреть возможность чтения сносок голосом.

**Comment by SergTSA** [comment]
при чтении голосом нужно решить единый подход к формированию текста, направляемого для озвучивания в движок ттс. 

некотрые движки артикулируют некоторые знаки препинания, напрмер.

**Comment by plotn** [comment]
@SergTSA, напиши подробности. Единый то единый - но какой?

**Comment by plotn** [comment]
насчет голоса так и не решили, но уж чо уж. Если надо - открываем новый тикет
