### ISSUE TITLE
Лишний вызов Formatting document после словаря

### ISSUE THREAD

**Issue by outlogic** [plotn/coolreader#110]
После вызова словаря и закрытия последнего при вовзрате в CoolReader правильно отображается нужная страница, но тут же возникает пустая страница с сообщением "Formatting document", после чего страница перерисовывается вновь.

А, например, при выделении текста, вызове диалога расшаривания и возврате в приложение подобная проблема отсутствует.

В версии на гугл плей возврат осуществляется к предыдущей странице, после чего происходит форматирование и вызов нужной страницы.

**Comment by plotn** [comment]
Уточните какой используется словарь

**Comment by outlogic** [comment]
Словарь MDict. Спасибо.

**Comment by outlogic** [comment]
Попробовал Lingvo и Lingvo Minicard, подобного переформатирования нет, но при этом на e-ink устройстве вместо словаря появляется чёрный прямоугольник.

Также попробовал BlueDict (выбрал в настройках GoldenDict/ColorDict), после чего при переводе появляется окошко, позволяющее выбрать GoldenDict Free, MDict, BlueDict для запуска один раз или постоянно. При этом после закрытия BlueDict тоже переформатирование происходит.

**Comment by plotn** [comment]
В этих словарях разбираться не буду, извините. Рекомендации даны на 4пда.
