### ISSUE TITLE
Концепция статистики

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#120]
Основные параметры:
Книга:
- среднее количество символов на странице;

Замер - единичная отметка о статистике. Хранить надо несколько замеров, постепенно заменяя самые старые (кольцом).

Условия для замера. 
1. Последовательное чтение Х страниц (20).
2. Чтение каждой страницы не более Х1 и не менее Х2 секунд (в зависимости от количества символов).

Включение замера в статистику.
Если менее 10 замеров - просто записываем. Если более - используем персентиль чтобы откинуть выбросы.

**Comment by plotn** [comment]
кажись даже и работает ;)))

**Comment by levushkin** [comment]
@plotn Осталось вынести в интерфейс
