### ISSUE TITLE
Интеграция с Литрес

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#121]
Интеграция

**Comment by levushkin** [comment]
@levushkin Написать письмо в Литрес

**Comment by levushkin** [comment]
[Пример партнёрки](https://www.litres.ru/o-kompanii/partnerskie-programmy/referalnye-partnery/#q-4-2)
[Описание API и возможных схем интеграции](https://docs.litres.ru/pages/viewpage.action?pageId=8161410)

**Comment by levushkin** [comment]
Партнёрский статус получен

**Comment by plotn** [comment]
@levushkin , в Соларе я зарегистрировался полноценно.
мы по второй схеме с литрес будем работать?

**Comment by plotn** [comment]
Пока поселю тикет в текущий майлстоун, делать буду долго, предлагаю перемещать его между мэйлстоунами все время, чтобы он был перед глазами. @levushkin , мне нужна твоя помощь - разберись как получить все ключи для запросов, погоняй пару-тройку в постмане, убедись что все работает, после чего отдай все это мне - начну уже все делать "по нормальному".

**Comment by levushkin** [comment]
> @levushkin , в Соларе я зарегистрировался полноценно.
> мы по второй схеме с литрес будем работать?

Ты про эти схемы: https://docs.litres.ru/pages/viewpage.action?pageId=8161410 ? Если так, то ты уверен, что мы потянем «Биллинг работает на стороне партнера, а партнер безналом расплачивается с ЛитРес»? Давай оффлайн обсудим

**Comment by plotn** [comment]
@levushkin , закрыть может уже?

**Comment by levushkin** [comment]
Можно. Но не нужно. Давай скачивание книги добьём? @plotn
