### ISSUE TITLE
Недавние, прочитанные и т.д.

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#125]
Разборки с Jurik_Phys : https://4pda.ru/forum/index.php?showtopic=191747&view=findpost&p=95923727

**Comment by levushkin** [comment]
@levushkin Привести описание того, как это воспроизвести

**Comment by levushkin** [comment]
Из последнего: [4pda](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=97580517) - есть инструкция, как воспроизвести
Чуть раньше: [4pda](https://4pda.ru/forum/index.php?s=&showtopic=191747&view=findpost&p=95923727) - постановка проблемы

**Comment by plotn** [comment]
дыкть!
