### ISSUE TITLE
Не отключать яркость

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#156]
при входе в настройки

**Comment by levushkin** [comment]
@levushkin При переходе в настройки яркость бьёт по глазам - найти коммент на 4pda

**Comment by levushkin** [comment]
Из последнего: [4pda](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=97580517)
Чуть раньше: [4pda](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=97232280)

**Comment by plotn** [comment]
Сделал!!! но еще не зарелизил

**Comment by plotn** [comment]
И залито на гуглдрайв
