### ISSUE TITLE
Социальные фичи

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#157]
Так как у нас есть сайт, то можно через него делать прекрасные штуки, такие как:
1. Сохранение позиции чтения и закладок через него;
2. Можно вывести статистику "столько то еще пользователей читает/прочитало эту книгу"
3. А можно даже им написать и попросить ее ;) Но тут надо обязательно настройку о "деанонимизации".
4. Ну и еще напридумывать ;)

**Comment by levushkin** [comment]
Решили, что не будем браться за такую задачу
