### ISSUE TITLE
Сделать независимую от основной ветки версию программы.

### ISSUE THREAD

**Issue by Demanih** [plotn/coolreader#16]
Сделать версию программы, или отдельную ветку, в которой все настройки будут храниться не в стандартной ".cr3" а, например, в ".cr3plotn" что, вместе с установкой данной версии как отдельное от основной программы приложение, позволит иметь на телефоне её независимую версию. При этом если бы при первичном запуске (если на телефоне ещё нет папки ".cr3plotn") программа бы брала (переносила) все базы из стандартной ".cr3" создавая на его основе свою ".cr3plotn", было бы вообще круто!

**Comment by plotn** [comment]
cr3e, без точки. Переносить из стандартной не планирую.
(еще не опубликовано, но уже реализовано)
