### ISSUE TITLE
mp3/mp4 в папке books

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#163]
**Версия 2020.06.13.1**

При наличии в папке books файлов mp3/mp4 наблюдается одно из событий:
1. Приложение вылетает при скролле в папке books (лечится удалением cr3e)
1. Файлы отображаются в списке книг, чего быть не должно:
![image](https://user-images.githubusercontent.com/60091524/84814043-904f2b80-b019-11ea-83f4-f155a3781bc5.png)
1. Проблемы с вылетом/отображением лишних файлов не возникает, но приложение создаёт папку empty, в которой mp3/mp4 файлы присутствуют

[4pda](https://4pda.ru/forum/index.php?showtopic=995536&st=0#entry97229001)

**Comment by plotn** [comment]
Нужны проблемные файлы. Вот я щас навскидку закинул квин в папку букс. Мп3. И ничего, не видно файла.
Была одна из версий с косяком (до кновнридера), но тут не факт что этот случай. 
Короче - каннот репродьюс

**Comment by levushkin** [comment]
@levushkin Дать @plotn файл, который убивает приложение

**Comment by levushkin** [comment]
У меня стабильно повторяется на этом файле: 
[20200614_225851.zip](https://github.com/plotn/coolreader/files/4809966/20200614_225851.zip)

**Comment by plotn** [comment]
Ничего я не понял тут. Указанный тобой файл закинул в папку "букс" в архиве и в распакованном виде. Ничего не вылетает. Файл просто игнорируется и в списке не показывается. Где создается папка "эмпти" я также не понял ;)))

@levushkin , давай убирать из мэйстоуна и дальше продолжать общаться по этому кейсу ;))

**Comment by levushkin** [comment]
Вот и наш товарищ с 4pda пишет, что не повторяется больше
