### ISSUE TITLE
Долго переключается между списками

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#165]
Пользователь 4pda:

> 1. Отсканировал
> 2. Захожу в Авторы - список формируется быстро
> 3. Захожу в Название или в Серии - приходится ждать 20-40 секунд, чтобы список обновился

**Comment by plotn** [comment]
Там такой адский код, что прям ваще.
Надо все переписывать.
Договорись с ним чтобы он нам всю библиотеку отдал, нам чтобы было на чем тестировать.

**Comment by levushkin** [comment]
Пользователь 4pda:
> Все отлично переключается, но есть ещё косячок. Всё как говорил - сначала туго, а потом:
> Нажимаю на Автор - сначала все быстро переключается, потом нажимаю  "Название" - начинается тупняк (ждать приходится 40 сек), потом на Автор тоже малость  тупит.
> А вот все другие папки (серии, рейтинг, жанр, год публикации, дата книги Дата файла и документа.) - всё отлично.
> Т.е. остались с косяками две папки: Автор и Название

Пользователь поделится своей библиотекой, чтобы можно было попробовать воспроизвести

**Comment by levushkin** [comment]
@plotn Ссылка на библиотеку у тебя в почте

**Comment by plotn** [comment]
Это основная работа. Полностью переделаны внутренние механизмы формирования библиотеки, т.е. выборок по:
- Серии, 
- Авторы,
- Жанры,
- Даты (книги, документа, файла, публикации),
- Результаты поиска.
Добавлено соответствующее кэширование. Надо объяснять всем, что первые вызовы (однократно) будут тоже медленно - идет подсчет статистики, потом должно быть максимально быстро. При добавлении большого количества новых книг - тоже первый вызов медленно, потом снова быстро.

Переделана функция группировки элементов по начальным буквам.
