### ISSUE TITLE
Если в папке много книг, приложение вылетает при скролле

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#166]
Повторяется, если в папке от 1000 книг

**Comment by levushkin** [comment]
@levushkin Договориться с пользователем, чтобы поделился своей библиотекой

**Comment by levushkin** [comment]
Договорились, скоро получим доступ к библиотеке

**Comment by levushkin** [comment]
@plotn Ссылка на библиотеку у тебя в почте

**Comment by plotn** [comment]
Есть подозрение, что это тоже:
[https://github.com/plotn/coolreader/issues/166](url)

Для большей уверенности надо проверять. Пока закрою.

**Comment by levushkin** [comment]
@plotn Ты дал ссылку на этот же issue. В чём подвох?
