### ISSUE TITLE
Добавить настройку цвета теста в меню

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#167]
Обещали рассмотреть возможность на [4pda](https://4pda.ru/forum/index.php?showtopic=995536&st=0#entry97229405):

> Доработка не будет простой, попробуем поиграться с цветами. Вообще, планируем поработать над UI/UX, но не сейчас, т.к. сейчас главное - функции и максимальная стабильность работы приложения. Если среди нас есть неравнодушные, кто готов предложить готовые темы для оформления, милости просим в личку

**Comment by plotn** [comment]
Есть ощущение, что баг (вернее "особенность") несколько шире - регулируется яркость только основного окна, а все диалоговые окна идут с системной настройкой. Поэтому скорее нет необоходимости в индивидуальной настройке цветов, а лучше поразбираться с этим. Исходная точка для копания:

private void updateBacklightBrightness(float b, boolean warm) {

**Comment by levushkin** [comment]
Вспомнилось: [4pda](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=97231322)

**Comment by plotn** [comment]
Вроде бы ж мы сделали это
