### ISSUE TITLE
Объединять папки одинаковых авторов

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#171]
См. тему на [4pda](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=97233014)

**Comment by plotn** [comment]
Есть книга с двумя авторами (X и Y) имена начинаются с одной буквы (те же самые братья стругацких) - создается ясное дело два автора и в них одна и та же книга
Есть две папки с книгами в одной папке указано ФИО, а во второй только ФИ - попробовать объединить эти папки
допустим если есть совпадение с ФИ то не создавать папку.

**Comment by plotn** [comment]
[aliases.utf8.txt](https://github.com/plotn/coolreader/files/5189244/aliases.utf8.txt)
+см. переписку в alreaderx:
https://4pda.ru/forum/index.php?showtopic=945616&view=findpost&p=99686733

**Comment by plotn** [comment]
Сделано. Хотя было сильно непросто.
