### ISSUE TITLE
Книги *.cbr и *.cbz долго открываются, приложение вылетает (на примере *.cbr)

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#172]
Пользователь 4pda:
> Knownreader у меня книгу открывал на смартфон ровно 5 минут. Планшет просто не выдерживает и сразу программа вылетает. Moon reader открыла за 2 секунды

Книги: 
* [book1.zip](https://github.com/plotn/coolreader/files/4800831/book1.zip)
* [book2.zip](https://github.com/plotn/coolreader/files/4800832/book2.zip)

Скриншоты:
![Avatsr](https://user-images.githubusercontent.com/60091524/85064730-a9401400-b1b4-11ea-9a98-109dd1dac6bd.png)
![Screenshot_20200617-101021](https://user-images.githubusercontent.com/60091524/85064734-a9d8aa80-b1b4-11ea-8301-33d07c0c622b.png)

**Comment by levushkin** [comment]
Замечено новое поведение - книги *.cbr и *.cbz вообще не отображаются в списке книг

**Comment by plotn** [comment]
Есть у меня ощущение, что CB* файлы у нас тупо не поддерживаются.
Уберу я их поддержку из манифеста.

**Comment by plotn** [comment]
Нет поддержки этих файлов.
