### ISSUE TITLE
Книга *.chm долго открывается, приложение вылетает

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#173]
Пользователь 4pda:
> Программа открывает и не может не как загрузить книгу. У меня в режиме простояло 2 минуты, потом   программу отключил.

Книга: [book.zip](https://github.com/plotn/coolreader/files/4800844/book.zip)

**Comment by levushkin** [comment]
Наш товарищ с 4pda говорит, что проблема ушла. Закрываю

**Comment by levushkin** [comment]
А не, передумал )

**Comment by levushkin** [comment]
Проверил. У меня повторяется проблема. Прилагаю скриншот:
![173](https://user-images.githubusercontent.com/60091524/87848898-0252b300-c8ed-11ea-98b8-d3e1037f1a26.png)

**Comment by levushkin** [comment]
Повторяется и на другом произведении: [exbpa.zip](https://github.com/plotn/coolreader/files/4941359/exbpa.zip)
![173_2](https://user-images.githubusercontent.com/60091524/87849000-ee5b8100-c8ed-11ea-8cc0-7dd1b2a65be7.png)

**Comment by plotn** [comment]
https://github.com/koreader/koreader/issues/6482

**Comment by plotn** [comment]
@levushkin , починено вроде было в CR, прошу проверить
