### ISSUE TITLE
При выборе ExtSD или SD приложение вылетает

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#174]
Пользователь 4pda:
> В видео показана как ошибка происходит. Нажимаю на ExtSd и Sd вылет

Видео: [video.zip](https://github.com/plotn/coolreader/files/4800854/video.zip)

**Comment by plotn** [comment]
Все устройства очень разные. Без корректно собранного лога данный тикет бессмысленен.
@levushkin , попробуй, вдруг удастся договориться

**Comment by levushkin** [comment]
[смартфон.txt](https://github.com/plotn/coolreader/files/4808324/default.txt)
[планшет.txt](https://github.com/plotn/coolreader/files/4808325/default.txt)
[планшет2.txt](https://github.com/plotn/coolreader/files/4808323/2.txt)

**Comment by plotn** [comment]
прошу еще раз снять логи с самой свежей версией на гитхабе - добавил логов

**Comment by plotn** [comment]
судя по логам эта свежая ошибка которая была добавлена (а тут исправлена) когда мы боролись с "двумя одинаковыми" книгами (которые оказались просто в разных файлах) - когда добавили вывод книги, файла, архива.
