### ISSUE TITLE
Добавить возможность быстрого перехода по сериям/авторам

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#177]
А переход через "корень" долги

**Comment by levushkin** [comment]
[4pda](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=97576349)

**Comment by plotn** [comment]
+ в бук инфо (ссылки)

**Comment by plotn** [comment]
в разбивке авторов:
- все книги автора
- все серии автора
Без разбивки:
- все авторы серии

**Comment by plotn** [comment]
![Screenshot_1595610276](https://user-images.githubusercontent.com/11477081/88416713-58da5880-cde9-11ea-99bc-f4aff2203a99.png)
![Screenshot_1595610289](https://user-images.githubusercontent.com/11477081/88416715-5972ef00-cde9-11ea-8f9a-af91f238ab24.png)
Запилено таким вот образом - контекстное меню + инфо о книге.
