### ISSUE TITLE
Изменить обработку книг формата odt

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#185]
При открытии файла формата odt происходит следующее:
1. Книга преобразуется в  html (физически создаётся файл в папке converted)
1. Открывается html, причём часто оформление книги сбивается

Т.е. имеем 2 проблемы:
1. Засорение диска
1. Потеря оформления

**Comment by plotn** [comment]
Сделано в родительском проекте. У нас оставлена такая обработка только для ods, odp (если не наврал - короче таблицы и презентации)
