### ISSUE TITLE
На больших экранах (7+ дюймов) в режиме чтения тяжело тянуться до меню

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#186]
![image](https://user-images.githubusercontent.com/60091524/85617124-6922da80-b667-11ea-9d4e-087adc5dceb4.png)

**Comment by plotn** [comment]
Сделать настройкой - сверху панель, снизу кнопка (стрелка вверх), и то и то. 
Вообще решается вызовом стандартного большого меню, т.е. почти все для этого есть.

**Comment by plotn** [comment]
Сделал снизу кнопку, думаю нет смысла перегружать доп настройками...

**Comment by plotn** [comment]
@levushkin , а у нас есть тикет на "одинаковое название книги" ? а то я только вопрос с тулбаром решил..

**Comment by levushkin** [comment]
> @levushkin , а у нас есть тикет на "одинаковое название книги" ? а то я только вопрос с тулбаром решил..

@plotn #187
