### ISSUE TITLE
Неверно оформленные сноски в fb2

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#197]
Проблема:

1. Текст сноски не отличается от основного текста книги
1. Иногда сноска уезжает на другую страницу

**Comment by levushkin** [comment]
Как должно быть:
![image](https://user-images.githubusercontent.com/60091524/86452622-3d69b980-bd25-11ea-9fe5-bd8d74a57330.png)
Как есть:
![image](https://user-images.githubusercontent.com/60091524/86452657-49557b80-bd25-11ea-9a1d-37c23bd1e7ee.png)
![image](https://user-images.githubusercontent.com/60091524/86452631-4064aa00-bd25-11ea-982b-d0a61c7ba183.png)

**Comment by plotn** [comment]
1. Настраивается в цсс
2. В книгах обычных тоже бывает)

**Comment by plotn** [comment]
(цсс) я имею ввиду вкладка цсс настроек

**Comment by levushkin** [comment]
![image](https://user-images.githubusercontent.com/60091524/86492479-ebea1a80-bd76-11ea-8654-40f22819403e.png)
