### ISSUE TITLE
Научиться открывать csv как таблицу

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#198]
На основе [4pda](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=97450086)

**Comment by plotn** [comment]
Я, честно говоря, против. Мы ж не офисный пакет, у нас вообще таблицы вещь вторичная. А тут цсв тем более.

**Comment by levushkin** [comment]
Возможно. Но мы умеем docx, например. А ещё веб-ссылки открывать. Давай хотя бы как текст (*.txt) его открывать научимся?

**Comment by plotn** [comment]
не будем мы этого делать, я думаю. извините все участвующие ;)
