### ISSUE TITLE
Изменять размер текста пальцами, а не через настройки

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#199]
Пользователь 4pda:
> Увеличение текста не только через настройки, ну и возможность с помощью двумя пальцами по экрану

**Comment by plotn** [comment]
Есть на эту тему мысли - щипок вертикальный, горизрнтальный (изменение полей), диагональный - размер шрифта. Двумя пальцами вверх/вниз - перемотка +- глава. Также тут же - починить управление перемоткой жестами. А то она ориентацию не чувствует.

**Comment by plotn** [comment]
+ пример измененного текста (размер)

**Comment by plotn** [comment]
Три пальца - меню

**Comment by plotn** [comment]
След, пред глава, можно несколько.
Удвоить питч
Maxlines=2

**Comment by plotn** [comment]
Проверка на значение при отпускании пальцев
