### ISSUE TITLE
Разные настройки на разных устройствах

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#200]
На смартфоне настройка есть:
![image](https://user-images.githubusercontent.com/60091524/86494220-0d4e0500-bd7d-11ea-9029-44043f5f3ba0.png)
На планшете настройки нет:
![image](https://user-images.githubusercontent.com/60091524/86494213-07582400-bd7d-11ea-832e-96b9c55171da.png)

**Comment by plotn** [comment]
Это зависит от открытого документа - епуб, фб2, тхт, хтмл. Скорее всего не баг.

**Comment by levushkin** [comment]
Not a bug
