### ISSUE TITLE
При скролле приложение вылетает

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#204]
Пользователь просто пытается скроллить. Лог во вложении: 
[2020-07-03-19-56-13.txt](https://github.com/plotn/coolreader/files/4880714/2020-07-03-19-56-13.txt)

**Comment by levushkin** [comment]
Сюда же:
> Ошибка при нажатии на скролл

Лог: [204_bag.txt](https://github.com/plotn/coolreader/files/4941585/204_bag.txt)
Скриншот:
![image](https://user-images.githubusercontent.com/60091524/87851928-1e168300-c906-11ea-9574-34427d2c2ee8.png)

**Comment by plotn** [comment]
По моему починено давно.
