### ISSUE TITLE
[feature requests] Выбор каталога в облаке в качестве корневого облачного каталога в программе

### ISSUE THREAD

**Issue by Jurik-Phys** [plotn/coolreader#205]
При наличии настроенной записи Яндекс.Диска и выборе "Yandex" из раздела "Открыть книгу из файловой системы/облака" главного экрана программы попадаем в корень этого самого Яндекс.Диска, в котором может содержаться много чего лишнего, не относящегося к процессу чтения книг и сбивающее с толку.

Даже в случае отдельной учётной записи, на облаке есть лишние данные. Так в корне Яндекс.Диска находится каталог настроек "KnownReader", содержимое которого к процессу чтения отношения не имеет и новичков может смутить.

Поэтому, представляется удобной возможность выбрать каталог из облака, который бы стал корневым при заходе в раздел "Yandex". При отсутствии выбранного ранее корневого каталога (переименовали его или удалили) можно снова показывать весь диск.

Поясню на примере. 
Пусть есть Яндекс.Диск со следующим содержанием:
-> Фото
-> Музыка
-> Рабочие материалы
-> Библиотека
----> Проза
----> Стихи
----> Прочитать

Сейчас, зайдя из программы на Яндекс.Диск всё это содержимое и будет отображено, включая каталоги Фото, Музыка, Рабочие материалы, но было бы удобно зайдя из читалки видеть только  "Проза", "Стихи", "Прочитать" т.е., содержимое каталога "Библиотека", который и хочется иметь возможность назначить корневым в программе.

**Comment by plotn** [comment]
ок, сделаем!

**Comment by plotn** [comment]
по хорошему конечно и дропбокс надо. Но пока оставим ;)
