### ISSUE TITLE
В книге формата fb2 не отрисовывается обложка книги при открытии

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#213]
Книга: [Mocart_I_Saleri_(A. Pushkin).fb2.zip](https://github.com/plotn/coolreader/files/4941376/Mocart_I_Saleri_.A.Pushkin.fb2.zip)
Вот что отрисовывает KR: 
![image](https://user-images.githubusercontent.com/60091524/87849284-f1577100-c8ef-11ea-9f51-f0da9416757f.png)
Яндек.Браузер и AlReader вместо этого отрисовывают минималистичную обложку

**Comment by plotn** [comment]
@levushkin , мне кажется это надо закрывать. Там где то в теме по CR было обсуждение именно этой книги - там в ней что то кривое внутри.

**Comment by plotn** [comment]
надо закрывать ;)
