### ISSUE TITLE
Непредвиденно меняется подсветка

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#215]
[4pda](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=97232280), Onyx Book Nova Plus
> После запуска KR подсветка сразу включается и яркость меняется. Включается только белый свет, желтый выключается полностью

**Comment by plotn** [comment]
Вот это еще учесть.

Furg0n
старый глюк от CR, актуально для e-ink устройств. Если уровень подсветки, в настройках программы, установлен на 9 и ниже, то фон текста заливается серым цветом, если 10 и выше, то все нормально, фон белый.
22:35Furg0n
И ещё одно неудобство, тоже актуально для e-ink, при выходе из режима чтения, подсветка выключается, а надо чтоб оставалась включенной.
08 дек.
10:35plotn
Я посмотрю. Первое вроде делал, но проверю
15 дек.
10:59plotn
Привет
11:00plotn
Фон текста заливается серым цветом - мне кажется я это лечил. Не могу воспроизвести на читалке
11:00plotn
Проверяй, делай скрины и фото
13:34Furg0n
Не работает ;( яркость ниже 10 и фон текста начинает сереть.
Подсветка при выходе в меню теперь сохраняется, но поломалось включение подсветки при запуске приложения. Т.е. открываем книгу, выставляем яркость подсветки, закрываем приложение, снова открываем, подсветка включается, но когда загружен текст книги она выключается. Проверял несколько раз. По поводу серого фона скрины будут такие же, как и ранее давал.
13:37Furg0n
Граница, когда фон текста равен фону меню - яркость 10%, если ниже, то начинает сереть, чем меньше яркость, тем серее фон.
14:04plotn
ладно, я еще посмотрю ;)
мистика или я слепой или на ливинстоне нет такого...
17:30Furg0n
Посмотрите по уровню яркости, может на ливингстоне уровень 10% не такой как мои 10%. Да и собственно это не главный глюк ;) неприятен был глюк, когда в меню выходишь и подсветка гасла, починили, но теперь сломалась при запуске приложения ;) Серость фона... ноги растут из CR.
19:17plotn
да, растут. И я помню что эти ноги убирал. Там прям характерно было.
20:19Furg0n
Видать он сороконожка ;) часть ног осталась

**Comment by plotn** [comment]
Год прошел, не думаю, что мы тут что то будем делать
