### ISSUE TITLE
ТТС, выделение предложения

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#223]
Несколько знаков препинания - немного криво выделяет

**Comment by plotn** [comment]
![kr_reading_problem](https://user-images.githubusercontent.com/11477081/87871946-6d6bba80-c9bd-11ea-886a-6d9739d44918.jpg)
![kr_reading_problem2](https://user-images.githubusercontent.com/11477081/87871947-6e9ce780-c9bd-11ea-9f50-29d178de66cd.jpg)
[_Prizyvayushchiy_Skverna_1_999999999-many_roC7GA_582634_fb2..fb2.zip](https://github.com/plotn/coolreader/files/4943508/_Prizyvayushchiy_Skverna_1_999999999-many_roC7GA_582634_fb2.fb2.zip)

**Comment by plotn** [comment]
@levushkin , можешь проверить и закрыть? Мне кажется все сделано.

**Comment by levushkin** [comment]
Проверил. Не повторяется. Закрываю
