### ISSUE TITLE
Объединить несколько папок с одинаковыми авторами

### ISSUE THREAD

**Issue by SvyatKV** [plotn/coolreader#232]
1. Есть книга с двумя авторами (X и Y) имена начинаются с одной буквы (те же самые братья стругацких) - создается ясное дело два автора и в них одна и та же книга
2. Есть две папки с книгами в одной папке указано ФИО, а во второй только ФИ - попробовать объединить эти папки
допустим если есть совпадение с ФИ то не создавать папку.

**Comment by plotn** [comment]
Дублирует #171, комментарий перенес, этот тикет закрываю
