### ISSUE TITLE
В некоторых случаях обложка книги закрывает текст

### ISSUE THREAD

**Issue by SvyatKV** [plotn/coolreader#234]
в некоторых книгах почему-то текст на обложку заходит, обложка и  “Моя большая книга” четкость картинки теряется 
![77](https://user-images.githubusercontent.com/61149954/88461388-ab7c4900-ceab-11ea-8966-6853d3bf56c4.png)
![78](https://user-images.githubusercontent.com/61149954/88461391-ad460c80-ceab-11ea-8509-55438df8b521.png)

**Comment by plotn** [comment]
https://github.com/koreader/koreader/issues/6490

**Comment by plotn** [comment]
Наверное не буду ничего делать сверх того, что сделано/не сделано в KOR/CR
