### ISSUE TITLE
Подправить папки 

### ISSUE THREAD

**Issue by SvyatKV** [plotn/coolreader#235]
![1](https://user-images.githubusercontent.com/61149954/88461451-3fe6ab80-ceac-11ea-8f0c-1e98b771283b.jpg)
![2](https://user-images.githubusercontent.com/61149954/88461452-4117d880-ceac-11ea-90dc-587b31f84294.jpg)
![3](https://user-images.githubusercontent.com/61149954/88461453-4117d880-ceac-11ea-9e28-fa011bcd0d3a.jpg)
смотри картинку № 1 как тут красиво выдало, 
а вот в картинке № 2 не очень то же подправить надо бы
картинка №2
![5](https://user-images.githubusercontent.com/61149954/88461507-c0a5a780-ceac-11ea-8132-50dd8db88986.png)
картинка №2
![6](https://user-images.githubusercontent.com/61149954/88461508-c1d6d480-ceac-11ea-887d-c7d9be08c6b9.png)

**Comment by plotn** [comment]
А в чем некрасивость?
Тут динамическая группировка

**Comment by SvyatKV** [comment]
> А в чем некрасивость?
> Тут динамическая группировка

1. Буква(ы) и троеточие 
2. Смесь в одной папке (Буква(ы) и троеточие и  полное фамилия и имя)
3. В картинке № 1 - Информативно представлено, то есть видны четко полные имена, во второй картинки не полностью прописаны имена папок.
..........
Я как вижу
1 папка (А, Б,В,Г, ... , Я (без троеточий)). Нажимаем на М (и тут все наименование идет на данную букву ) 
2 папка с годами (Год публикации (сделать например первая папка (1919 - 1999), вторая папка (2000 - 2010))) - но года берет из того что находится в папке.

**Comment by plotn** [comment]
Тут глобально другая идея. Она состоит в том, чтобы не скроллировать много, что губительно для еинка, но с другой стороны приходить куда надо, поэтому алгоритм адаптивный, в зависимости от количества файлов в папке и подпапке
