### ISSUE TITLE
Файлы в Яндекс диск

### ISSUE THREAD

**Issue by SvyatKV** [plotn/coolreader#236]
Программа видит абсолютно все файлы, которые есть в Яндекс.диске.

![20373224](https://user-images.githubusercontent.com/61149954/88461603-a61ffe00-cead-11ea-9ab5-ecb3732edb79.png)

**Comment by plotn** [comment]
Может быть и хрен бы с ним? Ведь та же картинка - она спокойно скачивается и спокойно заезжает либо на обложку либо в бэкграунд. Проблема решается (обходным маневром) установкой "домашей" папки для KR, в которой можно сделать все красиво и "не гадить" ;)

**Comment by SvyatKV** [comment]
> Может быть и хрен бы с ним? Ведь та же картинка - она спокойно скачивается и спокойно заезжает либо на обложку либо в бэкграунд. Проблема решается (обходным маневром) установкой "домашей" папки для KR, в которой можно сделать все красиво и "не гадить" ;)

Нууу, пожалуй согласен

**Comment by levushkin** [comment]
Задача про «домашнюю» папку в Яндекс.Диск: #205
