### ISSUE TITLE
Во время сканирования показывать дополнительную информацию

### ISSUE THREAD

**Issue by SvyatKV** [plotn/coolreader#237]
Переработать вид сканирования как указан на картинках. 
Во время сканирования сделать так, что бы показывала процент отображения
![Screenshot_2020-07-26-22-03-44](https://user-images.githubusercontent.com/61149954/88487287-5d8b4200-cf8c-11ea-9fd0-5ace4d8b6c7c.png)
![Screenshot_2020-07-26-22-03-50](https://user-images.githubusercontent.com/61149954/88487288-5ebc6f00-cf8c-11ea-916f-b17820fc1d07.png)

**Comment by SvyatKV** [comment]
Для удобства создать отдельное окно сканирование со всей информацией которая будет выводиться в отдельную форму.

**Comment by plotn** [comment]
добавить также кнопку по очистке мертвых ссылок

**Comment by plotn** [comment]
Сделан диалог обслуживания библиотеки. Создаем новые тикеты на основе него и реализованного в нем.
