### ISSUE TITLE
История поиска в словаре, автопополнение пользовательского словаря

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#238]
1. (сделано) Подвязывать перевод из пользовательского словаря (в историю переводов, если имеется)
2. (мне кажется полностью автоввод нафиг не нужен, а кнопка там имеется, т.е. ну да, два лишних тапа, но пофиг, учитывая будущий микс пользовательского словаря и истории перевода в нижней панели) Автоввод перевода в пользовательский словарь (настройкой) - при онлайн переводе

**Comment by plotn** [comment]
Может быть здесь еще подумать вот над чем - сейчас у нас есть пользовательский словарь "просто на слова" (хоть и с привязкой из какой книги этот перевод приехал). Проскакивала мысль персонизации переводов по книге, т.е. возможность разрешить сохранение перевода одного и того же, но из разных книг, при этом показывать в приоритете "из своей книги", а потом "как пойдет" (либо из всех, либо из первой попавшейся - подумать). И тут можно кстати обыграть, показывая название книги, из которой перевод "был рожден" (если она - не та, что читаем).

**Comment by plotn** [comment]
плюс выгрузка истории поиска (вся / эта книга / топ Х) для линго квиз (заодно покрутить, вдруг увлечет)

**Comment by plotn** [comment]
https://medium.com/@ismailnurudeen/using-the-text-processing-intent-in-android-3e17d2d53fbd

**Comment by levushkin** [comment]
У этой задачи ноги растут отсюда: [4pda](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=98551098)
