### ISSUE TITLE
Поиск слов по страницам

### ISSUE THREAD

**Issue by SvyatKV** [plotn/coolreader#240]
Слово "Браннер" ввёл, программа нашла, но не выделило его. 
![20413728](https://user-images.githubusercontent.com/61149954/88629006-64fb3a00-d0b7-11ea-9b58-9c20fa7755b2.png)

https://stackoverflow.com/questions/38509419/highlight-text-inside-a-textview

**Comment by plotn** [comment]
![Screenshot_1595959968](https://user-images.githubusercontent.com/11477081/88704707-25fcd100-d117-11ea-994f-0e77931f1b42.png)

**Comment by plotn** [comment]
Понятно, что мы выводим не всю страницу, а только начало (привет либрера, у тебя круче). Но там где там - там там.

**Comment by plotn** [comment]
убрать чувствительность к регистру
