### ISSUE TITLE
Не отображаются файлы *.cbr

### ISSUE THREAD

**Issue by SvyatKV** [plotn/coolreader#254]
Есть файлы cbr, если зайти из программного файлового менеджера (coolreader и KnownReader) обе программы его не видят.
НРешиф поэкспериментировать с названиями файлов получилось:
1. Убрал две точки в названии было "Орлов Б. Н. растения.chm" после изменения стало "Орлов растения.chm" программа coolreader появилась в списке "открыть с помощью" 
c knownreader'ом все хорошо видет все
2. Теперь что касается с cbr было "2020.03 terminator.cbr" после изменения стало "terminator.cbr" coolreader так и так не видет.
3. Knownreader не видет cbr в своём файловом менеджере. А вот через сторонний менеджер видна прога.
=====
Разобраться почему не отображаются файлы  *.cbr во внутреннем файловом менеджере

1.  [Орлов Б.Н. - Ядовитые животные и растения СССР.zip](https://github.com/plotn/coolreader/files/5029081/-.zip)
2.  https://yadi.sk/d/vOhxIuWpA0VKUQ

**Comment by levushkin** [comment]
См. [комментарий](https://github.com/plotn/coolreader/issues/172#issuecomment-654400367) к #172
