### ISSUE TITLE
Не отображается обложка книги

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#255]
SvyatKV:
> KR при открытии файла не отображает в начале страницы обложку книги: [3.+.+.fb2.zip](https://github.com/plotn/coolreader/files/5029869/3.%2B.%2B.fb2.zip) . Gроверил в AlreaderX (ПК windows и андроид) - обложку показывает

**Comment by plotn** [comment]
related to parent project

**Comment by plotn** [comment]
https://github.com/koreader/koreader/issues/6493

**Comment by plotn** [comment]
Сделано в родительском проекте
