### ISSUE TITLE
Некорректное отображение первой страницы книги

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#256]
SvyatKV:
> Криво показывает первая страница: [Mocart_I_Saleri_.A.Pushkin.fb2.zip](https://github.com/plotn/coolreader/files/5029883/Mocart_I_Saleri_.A.Pushkin.fb2.zip)
![image](https://user-images.githubusercontent.com/60091524/89440776-d50f5d00-d754-11ea-9923-98399cb25fb2.png)

**Comment by plotn** [comment]
https://github.com/koreader/koreader/issues/6492
