### ISSUE TITLE
Ynd - переводчик

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#283]
Какое то там у них изменение на облако. Изучить и переделать...

**Comment by plotn** [comment]
кажись все стало платным (((
https://cloud.yandex.ru/prices#calculator

**Comment by plotn** [comment]
https://www.maultalk.com/topic245964s10.html

**Comment by plotn** [comment]
https://cloud.yandex.ru/docs/translate/operations/translate - по этому мануалу все работает, осталось только цены узнать

**Comment by plotn** [comment]
остался листлэнг

**Comment by plotn** [comment]
И en-US = en

**Comment by levushkin** [comment]
[yandex.translate.api.pdf](https://github.com/plotn/coolreader/files/5219928/yandex.translate.api.pdf)
