### ISSUE TITLE
Cloud - удаление позиций после прочтения книги

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#289]
... в облаке.
Также проверить, что файлы в облаке подчищаются, а то были сомнения

**Comment by levushkin** [comment]
Источник: [H0B с 4pda](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=99547506)

**Comment by plotn** [comment]
Добавить кнопку в само окно с позициями, добавить пункт в клауд меню

**Comment by plotn** [comment]
Тут все сделано. Можно конечно еще как то сделать выпадающее меню при установке статуса "прочитан" не заходя в саму книгу. Но мне честно говоря уже лениво, так как и так есть куча способов сделать это.
