### ISSUE TITLE
При выделении текста происходит вылет

### ISSUE THREAD

**Issue by SvyatKV** [plotn/coolreader#291]
При выделении текста в moonreader, браузер вивальде  программа knowreader вылетает.
Парадоксально, сделал те же манипуляции в AlreaderX -  knowreader не вылетает, а просто открылась.
Прикладываю лог файл
[2020-09-13-16-00-22.txt](https://github.com/plotn/coolreader/files/5220506/2020-09-13-16-00-22.txt)

**Comment by plotn** [comment]
последствия перехода на androidx....
