### ISSUE TITLE
Баг открытия файла с некорректным названием 

### ISSUE THREAD

**Issue by SvyatKV** [plotn/coolreader#296]
[04+-+Куда+вас,+сударь…+занесло.zip](https://github.com/plotn/coolreader/files/5254900/04%2B-%2B.%2B.%2B.%2B.zip)
Лог файла на некоторых смартфонах происходит вылет при открытии файла
[2020-09-21-08-33-18.txt](https://github.com/plotn/coolreader/files/5254906/2020-09-21-08-33-18.txt)
Такая проблема возникла при открытии книги из файлового менеджера из папки dowload, а так же и из внешней и внутренней памяти выдаёт одну и ту же ошибку при открытии файла.
ПС проверил в koreader все нормально открылось

![Screenshot_2020-09-21-08-21-25](https://user-images.githubusercontent.com/61149954/93760473-bede3300-fc14-11ea-9535-99d26c934f86.png)
========
Эта проблема возникает из-за того что в названии файла присутствует троеточие

**Comment by plotn** [comment]
@SvyatKV , проверь пожалуйста на будущих версиях, когда мы изменения из upstream вользем (примерно через неделю две)

**Comment by plotn** [comment]
@SvyatKV  - это должно быть в текущем билде исправлено (который еще не вышел)

**Comment by plotn** [comment]
https://drive.google.com/file/d/1QFd-4ppChwNDKlSPUfcOO6GSPqtcuTrs/view?usp=sharing
https://drive.google.com/file/d/1qnkOecGq87i3So_jxmEjvOs1ZjR1qdPV/view?usp=sharing

**Comment by plotn** [comment]
Это актуально ещё?

**Comment by levushkin** [comment]
Не актуально. Закрываю
