### ISSUE TITLE
Litres: поиск подкатегорий

### ISSUE THREAD

**Issue by KnownReader** [plotn/coolreader#309]
[r_search_collections] Поиск по подборкам (коллекциям)
[r_search_genres] Поиск по жанрам и тегам
[r_search_persons] Поиск по персонам (авторам, чтецам, переводчикам и др.)
[r_search_sequences] Поиск по сериям

**Comment by plotn** [comment]
По жанрам 2 кнопки серч вместо одной - дусерч и шоу он жанрес

**Comment by plotn** [comment]
пагинация

**Comment by plotn** [comment]
По авторам - дескрипшн и картинка

**Comment by plotn** [comment]
При пагинации не забыть убрать группировку

**Comment by plotn** [comment]
всем подпапкам свой айтем и свои картинки, включая пагинационные

**Comment by plotn** [comment]
в жанрах обеспечить заход не в финальный жанр, а в "папку папок"
