### ISSUE TITLE
Не открывается в википедии полная статья

### ISSUE THREAD

**Issue by SvyatKV** [plotn/coolreader#324]
Во время открытия полной статьи (словарь - Википедия) - программа жутко долго думает, происходит с Автором - Федор Достоевский и его некоторыми произведениями (например - Идиот статью нормально открыл)
Но проверял с другими авторами выборочно 3 штуки все нормально.

Прикрепляю лог - файл
[2020-10-15-07-19-23.txt](https://github.com/plotn/coolreader/files/5382526/2020-10-15-07-19-23.txt)

**Comment by SvyatKV** [comment]
Скорее всего есть и еще косяки с другими авторами надо проверять

**Comment by plotn** [comment]
Точно надо, что ты выбирал, лучше даже скринами

**Comment by SvyatKV** [comment]
Все что выбирал указано выделено на картинках:
![photo_2020-10-15_08-15-15](https://user-images.githubusercontent.com/61149954/96090373-c79eed80-0ed0-11eb-932f-3ac5d12c6a4b.jpg)
![photo_2020-10-15_08-15-30](https://user-images.githubusercontent.com/61149954/96090378-c8d01a80-0ed0-11eb-86c1-6671d337696c.jpg)
![photo_2020-10-15_08-15-43](https://user-images.githubusercontent.com/61149954/96090380-c968b100-0ed0-11eb-8d0f-8da0f0965d8a.jpg)
Может пригодится на всякий случай книга
[Том 6. Идиот.zip](https://github.com/plotn/coolreader/files/5383092/6.zip)

**Comment by plotn** [comment]
Фиг его знает пока что делать. Валится jsoup

**Comment by plotn** [comment]
Не буду я наверное это чинить, так как в jsoup трабл. прости друг ;)
