### ISSUE TITLE
Ошибка при настройке цветовой температуры

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#351]
Комментарий от пользователя:
> Но используя её на Еlnk экране,заметил  баг.Зайдя в программу регулировка цветовой температуры меняется автоматически цвет как сепия. Причём изменения остаются и после выхода с программы (с) Александр через support@knownreader.com

**Comment by plotn** [comment]
А можно я тебе тут обраточку оформлю?: https://www.youtube.com/watch?v=fX1rhetWH24&feature=youtu.be

**Comment by plotn** [comment]
Закрываем, думаю мы не разберемся уже после времени
