### ISSUE TITLE
Добавить интеграцию с Anki

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#359]
Пользователи с habr'а просят:
- https://habr.com/ru/post/529244/#comment_22337604
- https://habr.com/ru/post/529244/#comment_22337770

Пример:
> Поддрежу комментатора выше. Мне бы хотелось, чтобы в процессе чтения можно было отметить слово или фразу для добавления в карточку. Затем зайти в пункт меню, отвечающий за импорт заметок, выбрать «импрортировать в Anki» и читалка сама сформирует колоду для Anki по заданному шаблону и отправит в облако. Очень желатльно еще сохранять в карточку контекст, в котором используется слово. Возможно все предложение. И теги на источник, чтобы можно было отсортировать карточки по книгам при обучении.

**Comment by plotn** [comment]
Про контекст:

Что такое «контекст»? Вот что у нас есть:
1. Текст (слово или несколько), которые мы переводим;
2. Перевод (или толкование) текста;
3. Книга, автор — которые мы читаем и в котором п.1 и 2 возникли;
4. Предложение, из которого извлечен п.1.;
5. Или целый абзац…
6. Еще можно название главы;
7. Ну, дата время — понятно

**Comment by plotn** [comment]
По этой задаче - осталось сделать сохранение (и обработку) контекста и цвета закладок в БД и далее по всему движку

**Comment by plotn** [comment]
А не, цвет закладок - в отдельном тикете есть

**Comment by plotn** [comment]
в БД пишется короткий и длинный контекст, в целом работу по Анки можно считать завершенной

**Comment by msinty** [comment]
> выбрать «импрортировать в Anki» и читалка сама сформирует колоду для Anki по заданному шаблону и отправит в облако.
данный функционал уже внедрен? не могу понять.
