### ISSUE TITLE
Баг с обложкой

### ISSUE THREAD

**Issue by SvyatKV** [plotn/coolreader#367]
[Планета охотников (Сборник).zip](https://github.com/plotn/coolreader/files/5684379/default.zip)
![Screenshot_2020-12-04-09-05-14](https://user-images.githubusercontent.com/61149954/102007522-dd972600-3d3a-11eb-8c5c-897201eb20d4.png)
![Screenshot_20201203-185657](https://user-images.githubusercontent.com/61149954/102007523-df60e980-3d3a-11eb-9518-2aac39ff0f1b.png)

**Comment by SvyatKV** [comment]
1 фотка вид с планшета
2 фотка вид со смарта

**Comment by plotn** [comment]
https://4pda.ru/forum/index.php?showtopic=995536&view=findpost&p=104229093
