### ISSUE TITLE
Работа со словарем Википедия

### ISSUE THREAD

**Issue by DmitryPavlov44** [plotn/coolreader#4]
1. Попытался поставить в качестве словаря Википедию. Выделяю в книге слово, выбираю иконку словаря - открывается приложение Википедия на стартовой странице, выделенного слова нигде нет.
2. Выбираю слово в тексте в режиме выделения, нажимаю "поделиться", выбираю Википедию - выводится окно вики с текстом, включающим перед самим словом данные о книге и местонахождении в ней.

**Comment by plotn** [comment]
+ Здесь же - внедрение настройки шаблонов при отправке текста во внешние приложения

**Comment by plotn** [comment]
Починено в дропбокс билде. От шаблонов отказался в пользу механизма "send to" в словарях
