### ISSUE TITLE
Anki - отметка цветом

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#403]
хоть и гарксон исчез...

**Comment by plotn** [comment]
еще попросили вариант:
слово<br>Предложение, содержащее <b>слово</b>

**Comment by plotn** [comment]
Если цвет не делаем, то предлагаю закрывать. 

msinty?

**Comment by msinty** [comment]
Предлагаю упростить окно "уточнения действия Отправить в".
Пример окна:
========================
- [ ] Выбранный текст
- [ ] Контекст 
- [x] Контекст с выбранным текстом
- [ ] Выбранный текст <br> контекст        
========================

Далее, выбрав одну из опций, пользователь получает доступ к параметрам форматирования для данной опции, в отдельном окне.  Ниже этих параметров будет отображается предпросмотр форматирования.
Пример окна:
========================
выбранный текст
- [x] bold
- [ ] italic
- [ ] underlined
- [ ] text color
- [ ] text background
==
контекст
- [ ] bold
- [x] italic
- [ ] underlined
- [ ] text color
- [ ] text background
==
предпросмотр
_Lorem ipsum dolor sit amet, **consectetur** adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua._ 
========================
Думаю также стоит добавить CSS классы как для текста так и для контекста, предоставив пользователю самому настроить отображение средствами анки. Могу ошибаться, но помоему анки поддерживает данный [функционал](url="https://www.youtube.com/watch?v=F1j1Zx0mXME&yt%3Acc=on"):
<p class="KR_context">_Lorem ipsum dolor sit amet, <span class="KR_selection">**consectetur**</span> adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua._ </p>

**Comment by plotn** [comment]
@msinty, то, что ты предлагаешь - разумно и интересно. Но на текущей итерации хотелось бы более дешевого решения. Для меня это было бы - расширение списка "Уточнение действия ..."
Сейчас там 8 пунктов. Давай добавим еще несколько вариантов, если нужно и пока на этом остановимся.

**Comment by plotn** [comment]
Кажись никому не надо уже ))) закрою
