### ISSUE TITLE
Добавить поддержку *.cbr и *.cbz

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#414]
Пользователь оставил отзыв:
> This looks like a very promising app. There are A LOT of options which is what I am looking for. Unfortunately, it doesn't support CBZ and CBR comic book files which is what most of my library consists of. If this gets added, I might switch to this app as my main reading app.

Раньше уже занимались этим, но не осилили: #172 - если будет возможность, было бы неплохо добавить поддержку этих форматов

**Comment by plotn** [comment]
да не, пожалуй и в этот раз не осилим ;) некому делать
