### ISSUE TITLE
Combo-кнопка с 2 сценариями

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#415]
По [запросу пользователя](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=104609338):
> Можно предложить хотелочку для анализа?
> Combo-кнопка которая отправит в анки поля опреленые пользователем по следующим сценариям.
> Сценарий номер 1, "конструктор пользовательских полей":
> Пример:
> - поле КР текст -> поле анки номер 1 (уже поддерживается)
> - поле КР "перевод онлайн лингво" + html tag (к примеру \<br\>, \<hr\>) + поле KR длинный контекст -> поле анки номер 2
> 
> Сценарий номер 2, "выбор соответствия полей КР и Анки":
> Пользователь настраивает какому полю из КР соответствуют поля из Анки.
> Пример:
> - поле КР текст -> поле анки номер 1
> - поле КР перевод онлайн лингво -> поле анки номер 2
> - поле КР длинный контекст -> поле анки номер 3 (пользовательское)

Дальше был другой [комментарий](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=104615487):
> А вот смотри - настройка "Уточенние действия 'Отправить в'" - это не то, о чем мы говорим? Может туда добавить несколько вариантов. Т.е. например "выбранный текст <br> контекст". Тут был один товарищ, он просил выделение цветом добавить, но он исчез куда то (а мы просили его шаблоны его хотелок прислать).
> Насчет трех текстов - по моему нет, т.е. мы в анки только два текста умеем передавать. Если как то можно три ... то было бы хорошо.

**Comment by msinty** [comment]
Приветствую!
Спасибо за тикет!

Поэтапное воспроизводство сценариев:
[Сценарий номер 1, "конструктор пользовательских полей"](https://youtu.be/zBVn9o5jCoI)
[Сценарий номер 2, "выбор соответствия полей КР и Анки":](https://youtu.be/tYIrZpgdmLA)

Можно ли будет также скрыть всплывающее окно переводчика после добавления карточки?
Всех благ !

**Comment by msinty** [comment]
> А вот смотри - настройка "Уточенние действия 'Отправить в'" - это не то, о чем мы говорим? Может туда добавить несколько вариантов. Т.е. например "выбранный текст
контекст"

Уточнение действия относится к первому полю Анки.
Но не лишним был бы подобный функционал и для второго поля, с возможностью выбора контекста + онлайн перевода.
Но это отдельное пожелание.

**Comment by plotn** [comment]
@msinty , ты потерял интерес к проекту? имеет ли тикет смысл?

**Comment by msinty** [comment]
> @msinty , ты потерял интерес к проекту? имеет ли тикет смысл?

Привет, нет не потерял. Завал на работе небывалый. Как закончу дела, вернусь.
Если чем-нибудь могу помочь, пиши тута.

**Comment by plotn** [comment]
ну кажись скоро год уж как тикету. закрываю, за отсутствием интереса
