### ISSUE TITLE
Некорректно применяются настройки яркости

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#416]
Пользователь [написал](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=104618639):
> Со снятой галкой "при запуске использовать системную яркость" после входа/выхода в "Настройки" яркость сбрасывается на то значение, которое было при последнем выходе из KR

**Comment by plotn** [comment]
@levushkin , с тех пор куча всего изменилась. Если есть возможность подтвердить или опровергнуть - то ок, если нет, то закрываем.

**Comment by levushkin** [comment]
[Спросил](https://4pda.to/forum/index.php?s=&showtopic=995536&view=findpost&p=107286207), жду ответа. Надеюсь, **kaznelson** заряженный. Надеюсь, поможет :)

**Comment by plotn** [comment]
Тут по моему недавно было починено. Закрываю.
