### ISSUE TITLE
Настройка яркости свайпом работает плохо

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#417]
Пользователь [написал](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=104618639):
> Вывод внизу экрана значений яркости при её изменении свайпом выглядит всё так же плохо: значения накладываются на текст и пропадают слишком быстро. Результат - мазня/мельтешня. Можно ли их вообще отключить для еИнка? Ведь этот параметр всё равно регулируется "на глаз" - причём буквально

**Comment by plotn** [comment]
По моему я это сделал в итоге
