### ISSUE TITLE
Изменить процентные настройки яркости

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#418]
Пользователь [написал](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=104618639):
> Процентные значения яркости по прежнему способны вогнать в ступор неподготовленного юзверя. Если такие берутся из системы, то может стоит выводить абстрактный уровень, как в самом Onyx'е? Шкала у того же Livingstone на 33 части поделена, вдобавок нелинейная - вот и выводить "выкл, 1, 2, ... 32, макс"

**Comment by plotn** [comment]
Сделано и вроде даже и получше стало
