### ISSUE TITLE
Перенести настройки "Опции рендеринга" и "Уровень совместимости DOM"

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#420]
Пользователь [написал](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=104618639):
> "Опции рендеринга" и "Уровень совместимости DOM" на мой взгляд стоит убрать в "Редкие и экспериментальные". Понять что это такое у простого юзверя нет никаких шансов (даже невзирая на разъяснения), да и умолчальное их значение подойдёт подавляющему большинству. А то маячит, пугает, справки не даёт, дублируется в "Шрифтах" и "CSS"

Дальше ещё немного обсуждения:
> хорошая мысль. Но лучше тогда в "тонкие настройки шрифта", дополнительно переименовав их в "... рендеринга и шрифта"

**Comment by plotn** [comment]
сделал все что мог ;) 
https://4pda.ru/forum/index.php?showtopic=995536&view=findpost&p=104692165
