### ISSUE TITLE
Перенести информацию о профиле настроек в шестерёнку

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#421]
Пользователь [написал](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=104618639):
> Можно ли профиль настроек, который сейчас вверху выводится как "/s/e/cr3e/cr2.ini.profile1" сделать отдельным пунктом во вкладке "шестерёнка"? Сейчас на Livingstone опухнешь его нажимать; да и внешний вид "Настроек" эта демонстративно служебная строка здорово портит

Дальше немного [обсуждения](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=104620826):
> Мне кажется нехорошо будет. Да, щас выглядит несколько технически. Но профиль - это именно не еще одна настройка. А профиль переключает ВСЕ настройки на другие. Поэтому я его и вывел сильно отдельно. И поэтому я его и вывел, в принципе. Вообще работа с профилями в KR/CR очень запутанно сделана, я пытался хоть как то это дело "упрозрачнить".

**Comment by plotn** [comment]
Я туда вставил еще кнопку поиска по настройкам. Стало органичненько. Так, пожалуй, оставим
