### ISSUE TITLE
Сгруппировать действия во вкладках "Управление" и "Страница"

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#422]
Пользователь [написал](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=104618639):
> Ещё возникла такая мысля - может будет удобно, если во вкладке "Управление" сгруппировать действия для выделения (3->1) и отправки (2->1) подобно спецрежимам выделения?
> Также во вкладке "Страница" хорошо бы сгруппировать чисто еИнковские настройки обновления экрана (4->1). Настраиваются они крайне редко, а места в списке занимают много.

[Пояснение](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=104621254):
> Как-то так:
> 1. "Режим обновления экрана", "Интервал полного обновления", "Интервал отрисовки черной страницы" и "Длительность отрисовки черной страницы" - группируются в один раскрывающийся на отдельную страницу пункт "Обновление eInk-экранов >"
> 1. "Действие для выделения", "Действие для нескольких выделенных слов" и "Действие для выделения (длинный тап)" - группируются в один раскрывающийся пункт "Настройки действий для выделения >"
> 1. "Действие 'Отправить в'" и "Уточнение действия 'Отправить в'" - группируются в один раскрывающийся пункт "Настройки действия 'Отправить в' >"

**Comment by plotn** [comment]
п.3. пока не буду группировать, пока он не разросся, а там посмотрим.
