### ISSUE TITLE
Горизонтальное листание жестами стало вертикальным

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#424]
Пользователь [написал](https://4pda.ru/forum/index.php?s=&showtopic=995536&view=findpost&p=104629131):
> Тут ещё один момент всплыл: похоже что горизонтальное листание жестами справа налево (и обратно) повернулось на 90 градусов против часовой - и стало листанием по вертикали. По крайней мере у меня на крайней arm7-версии KR жест снизу вверх листает вперёд (и не важно: из левого нижнего угла в правый верхний, из правого нижнего в левый верхний, или вообще строго по вертикали), а жест сверху вниз соответственно назад...

**Comment by plotn** [comment]
Странное кино... Но починил. Не понятно только чем настройки "отслеживать" от "слева направо" отличаются, но не в этом уж тикете разбираться. Хотя, технический долг.
