### ISSUE TITLE
Сканирование - медленно и плохо

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#428]
попробовать разбить на мелкие папки, а то сейчас работает плохо

**Comment by plotn** [comment]
вроде с последней фичей стало норм. Осталось диалог прогресса переработать.

**Comment by plotn** [comment]
Статистика после массового сканирования

**Comment by SvyatKV** [comment]
После сканирования не отобразила сколько чего нашла, точнее выдало но нули показала. - Доработать.

**Comment by plotn** [comment]
нули означают что ничего нового не нашла.
