### ISSUE TITLE
Разобраться с выбором сканирование папок

### ISSUE THREAD

**Issue by SvyatKV** [plotn/coolreader#431]
![1](https://user-images.githubusercontent.com/61149954/110456953-30cf0980-80db-11eb-91d8-68461302f083.jpg)
![2](https://user-images.githubusercontent.com/61149954/110456955-3167a000-80db-11eb-96c8-94781d93742a.jpg)
1. Первая картинка это смартфон - тут порядок.
2. Проблема со 2 картинкой это планшет:
В разделе Внутреннее хранилище есть  sdcard1 (по сути это внешняя sd) и да получается все карты которые есть отнес во внутренние. И при сканировании внешняя sd сканирует внутреннюю память.

**Comment by plotn** [comment]
Разнесено по картам. Вроде даже и работает.
