### ISSUE TITLE
Улучшение TTS

### ISSUE THREAD

**Issue by zertyuiop** [plotn/coolreader#441]
В KnownReader скорость TTS имеет слайдер, но без индикации, так что непонятно, какая установлена скорость. Хотелось бы иметь подобное отображение. Также, если возможно, стоит установить пределы скорости от ~0.5x до хотя бы 3x-5x, с шагом 0.05x- 0.1x с возможностью точной установки скорости (вводом значения, или кнопками +-). По таймеру хотелось бы ввод значения вместо выбора из кучи значений от 0 до 100, и возможность запускать таймер/ устанавливать время из панели TTS, а не только из меню настройки.
Не знаю точно, баг это, или нет, но значение скорости не всегда запоминается.

**Comment by plotn** [comment]
Посмотри пожалуйста вчерашнюю версию - то, что ты хотел? Отметь что осталось или закрой тикет если всё норм

**Comment by plotn** [comment]
Видимо все ему понравилось ;)
