### ISSUE TITLE
Закрытие программы в решетке

### ISSUE THREAD

**Issue by SvyatKV** [plotn/coolreader#443]
Добавить кнопку закрытие программы 
![photo_2021-04-07_17-09-15](https://user-images.githubusercontent.com/61149954/113890800-29c81380-97cd-11eb-8595-4101353115d8.jpg)

**Comment by plotn** [comment]
@SvyatKV , а в какой то еще программе такое есть? У меня сомнение, что в андроиде этих кнопок - ограниченное количество и добавлять нельзя.

**Comment by plotn** [comment]
Ну, как хочешь. Закрою.
Если что - скажи, переоткрою.
