### ISSUE TITLE
Баг с открытием книги

### ISSUE THREAD

**Issue by SvyatKV** [plotn/coolreader#448]
Происходит открытие из файлового менеджера
![photo_2021-04-09_15-39-18](https://user-images.githubusercontent.com/61149954/114181142-cb746f80-9949-11eb-9406-d22e24b5b563.jpg)
Вот эти книги

книги вот здесь под моим постом
https://4pda.ru/forum/index.php?showtopic=191747&view=findpost&p=105873261

-Chrome Shelled Regios 1-25.epub ( 179,2 МБ )
Прикрепленный файлvoinstvennyiy_bog_asura.fb2 ( 70,32 МБ )

![photo_2021-04-09_16-00-46](https://user-images.githubusercontent.com/61149954/114183857-cbc23a00-994c-11eb-8486-5ebb154676df.jpg)
![photo_2021-04-09_16-00-52](https://user-images.githubusercontent.com/61149954/114183858-cc5ad080-994c-11eb-9f14-e6eb4aaba1b1.jpg)

**Comment by SvyatKV** [comment]
И еще один момент обнаружил
1. Если открыть книгу из **потока** то программа вылетает.
2. Если открыть книгу как файл - тут все хорошо

**Comment by plotn** [comment]
Думаю исправление было в KR
