### ISSUE TITLE
Некорректно работают ссылки

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#463]
От пользователя:
> The application is great but the links are not working. Everytime a link is clicked on it changes the page. My device is a Samsung Galaxy S6

**Comment by plotn** [comment]
@levushkin , ничерта ж не понятно....

**Comment by levushkin** [comment]
Уточню :)

**Comment by levushkin** [comment]
[Спросил](https://4pda.to/forum/index.php?s=&showtopic=995536&view=findpost&p=107286138)

**Comment by plotn** [comment]
че т не видел, чтобы тебе ответили ;) закрою ка я
