### ISSUE TITLE
Добавить настройку, чтобы убирать панель сверху

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#464]
От пользователя:
> Спасибо всем разработчикам за превосходную работу.Очень много тонких настроек.Хотел Вас попросить,сделать выбор убрать полоску  о прочитанном и отображении батареи.Читаю на электронной книге onyx boxx

**Comment by plotn** [comment]
@levushkin , уточнил бы ты у наших гуру (SergeyTSA, SvyatKV, kaznelson), может это все есть? В "настройки колонтитула и полноэкранного режима" ходил?

**Comment by levushkin** [comment]
[Спросил](https://4pda.to/forum/index.php?s=&showtopic=995536&view=findpost&p=107286138)

**Comment by plotn** [comment]
Короче есть у нас все это в настройках (и панель и колонтитул), ищи лучше ;)
закрываю
