### ISSUE TITLE
opds

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#48]
https://borchun.name/main/32-aktualnye-opds-katalogi.html

АСМОДЕЙ - http://asmodei.ru/opds/
Куллиб - http://coollib.net/opds
iknigi - http://iknigi.net/opds/
Fantasy World - http://f-w.in/opds
e-reading - http://www.e-reading.link/opds/
MAXIMA-LIBRARY - http://maxima-library.org/opds
LITLIB - http://fb.litlib.net
Android Club - http://smartoff.net/opds/
zone4iphone.ru - http://www.zone4iphone.ru/catalog.php
dimonvideo - https://dimonvideo.ru/lib.xml

Актуальные, новые и рабочие opds каталоги на февраль 2019
http://lib.rus.ec/opds
http://flibusta.is/opds
http://opdshome.uo1.net/samlib/
http://epubbooks.ru/index.xml
http://fb.litlib.net/
https://smartoff.net/opds/

**Comment by plotn** [comment]
Чтобы далеко не искать поделюсь своими ссылками на сервера.

Помимо встроенного http://flibusta.is/opds

Добавил
https://flibusta.appspot.com/opds/ https://flibusta.herokuapp.com/opds
http://flibustahezeous3.onion.link/opds
https://flibustahezeous3.onion.rip/opds
http://proxy.flibusta.net/opds
Последний юзать с включенным прокси

Кроме Флибусты есть еще каталоги и других библиотек

http://lib.rus.ec/opds
http://coollib.net/opds
http://iknigi.net/opds
http://f-w.in/opds
http://www.e-reading.link/opds
http://maxima-library.org/opds
http://fb.litlib.net/
http://opdshome.uo1.net/samlib/
http://bookserver.archive.org/catalog/
http://opds.oreilly.com/opds/
http://www.feedbooks.com/catalog.atom

И еще тут Список электронных библиотек (Пост papamuller #3389790)

**Comment by plotn** [comment]
+определение названия и иконки при добавлении

**Comment by plotn** [comment]
Вылет при скачивании, не удаляет

**Comment by levushkin** [comment]
@levushkin

**Comment by levushkin** [comment]
@levushkin Обновить список OPDS по умолчанию

**Comment by plotn** [comment]
уже, наверное, потеря актуальности
