### ISSUE TITLE
Книги открываются из потока откуда угодно (Onyx Boox Poke 3 на Anroid 10)

### ISSUE THREAD

**Issue by kaznelson** [plotn/coolreader#529]
На Onyx Boox Poke 3 (Anroid 10) книги по прежнему открываются из потока откуда угодно (кроме файл-менеджера самого KR) как _Имя.fb2[123456789.fb2.pack_

![Screenshot_20211013-123944](https://user-images.githubusercontent.com/90417439/137131074-38b993f9-a4ee-4396-8f7e-2ce67f3e8d86.png)];

**Comment by plotn** [comment]
не забыть тут же сделать настройку - при найденном файле не показывать диалог прихода внешнего документа

**Comment by plotn** [comment]
и тут же - переработать диалог внешнего документа, а то он больно он монстроидально смотрится

**Comment by plotn** [comment]
закрою все же. пусть немного помелькает ;)
