### ISSUE TITLE
После поиска нет возврата кнопкой "Назад" к месту текущего чтения

### ISSUE THREAD

**Issue by kaznelson** [plotn/coolreader#546]
После выхода из диалога поиска не работает возврат по программному/аппаратному действию "Назад" к тому месту, откуда начал искать. Открывается место предыдущего перехода (ну или корневое меню, если других переходов по тексту не было).

**Comment by plotn** [comment]
Я вот, честно говоря, не очень понял. Это про диалог поиска в книге? Или про диалог поиска книг? И куда какой переход нужен. Что то тычу, тычу... И не пойму.

**Comment by kaznelson** [comment]
Вот смотрите: надо мне найти некий текст. Вызываю диалог поиска, ввожу, нахожу, закрываю наэкранную панель поиска, читаю 2-3 страницы. Прочёл, вызвал меню чтения (Poke 3) или просто нажал "Back" (Livingstone), и в результате попадаю... в корневое меню, а вовсе не в то место, откуда я начал поиск.
Это некритично, если искал именно с целью продолжить чтение с найденного текста. Но вот если хотел просто освежить абзац-другой в памяти - крайне неудобно...

**Comment by plotn** [comment]
Сделал, но немного по своему, на форуме покажу
