### ISSUE TITLE
При перезапуске KR пропадают выделения текста (закладки)

### ISSUE THREAD

**Issue by kaznelson** [plotn/coolreader#549]
При перезапуске KR пропадают выделения со сделанных с помощью панели выделения закладок в тексте.
Если сделать ещё одну, то все выделения восстанавливаются.
В диалоге закладок при этом всё на месте, переход на закладки работает.
А вот долгий тап на сделанную ранее, но не подсвеченную после перезапуска закладку - не работает...

https://user-images.githubusercontent.com/90417439/145342432-c3add4bd-93f2-4b83-b7b2-de427a619d7d.mp4

**Comment by plotn** [comment]
вроде починил.
А что это у вас за шрифт на книге?
