### ISSUE TITLE
Принудительная заливка чёрным 5000 мс - экран остаётся чёрным

### ISSUE THREAD

**Issue by kaznelson** [plotn/coolreader#552]
При выставлении продолжительности принудительной заливки чёрным (т.е. для неподдерживаемых еИнков) в 5000 мс экран так и остаётся чёрным, пока в него не ткнёшь. При 4000 мс работает нормально.

**Comment by plotn** [comment]
@kaznelson , проверил и на поке и на смарте. Нормально вроде все.

**Comment by kaznelson** [comment]
Да, на крайнем релизе проблемы нет.
