### ISSUE TITLE
дооформить расчет статистики

### ISSUE THREAD

**Issue by SvyatKV** [plotn/coolreader#593]
Информативно дооформить
Недостаточно статистика (вам необходимо прочитать столько то страниц или что-то в таком духе)

**Comment by plotn** [comment]
@SvyatKV , вот как ты себе это видишь? для минимального расчета нужно чтобы пользователь прочитал пять страниц с примерно одинаковой скоростью. Чем больше будет таких "пятистраничных замеров", тем точнее будет расчет.
что и куда ты хочешь написать ? ;))))
