### ISSUE TITLE
Расширенный полноэкранный режим перестаёт работать

### ISSUE THREAD

**Issue by levushkin** [plotn/coolreader#594]
Пользователь:
> Если выйти из приложения, либо свернуть и открыть заново, расширенный полноэкранный режим перестаёт работать, пока не откроешь настройки и не выйдешь из настроек в режим чтения. А так, вполне годно, альтернатива известной читалке, с более гибкими и расширенными настройками.

@plotn нужно что-то ещё? Или этой информации достаточно?

**Comment by plotn** [comment]
ниче не нужно, это было когда то давно. 
вообще надо напрячься и все таки обновиться в маркете, раз уж нас, в принципе, любят
