### ISSUE TITLE
Меню чтения: не вмещаются длинные названия

### ISSUE THREAD

**Issue by kaznelson** [plotn/coolreader#637]
В меню чтения не вмещаются длинные названия - т.е. более двух слов (причём тоже не шибко длинных).
В связи с этим хорошо бы прикинуть возможность сокращения названий команд (с учётом их возможного использования ещё где-нибудь) или сделать псевдонимы для всех выезжающих меню.

![Screenshot_20220303-120854](https://user-images.githubusercontent.com/90417439/167360158-b12697bf-fcd0-410a-a5b6-7a376a57f5d0.png)

Предлагаю вот такие альтернативные/короткие наименования:

Беглый просмотр книги -> Беглый просмотр
Блокировка сенсорного экрана -> Блокировка экрана
Включить/выключить стили документа -> Вкл/выкл стилей
Восстановить настройки с облачного хранилища -> Настройки из облака
Восстановить позицию чтения из облачного хранилища -> Позиция из облака
Выбрать фоновую картинку / текстуру -> Выбрать фон
Загрузить закладки из облачного хранилища -> Закладки из облака
Личный словарь / цитаты / история поиска -> Личный словарь+
Меню облачного хранилища -> Меню облака
На последнюю страницу -> В конец книги
Настройки (с фильтрацией) -> Фильтр настроек
Онлайн супер комбо -> Онлайн суперкомбо
Открыть книгу из Dropbox -> Открыть из Dropbox
Открыть книгу с Яндекс.Диска -> Открыть с Я.Диска
Отправить книгу по Email -> Отправить почтой
Переключить автоформатирование текста -> Автоформат текста
Переключить ориентацию экрана -> Ориентация экрана
Переключить полноэкранный режим -> Режим экрана
Переключить словарь (однократно) -> Перекл. словарь
Показать системный диалог для настройки подсветки -> Диалог подсветки
Профиль настроек (переименовать - длинный тап) -> Профиль настроек
Режим выделения текста -> Выделение текста
Режим инспектора страницы -> Инспектор страницы
Сохранить быструю закладку -> Быстрая закладка
Сохранить в личный словарь (последнее выделение) -> В личный словарь
Сохранить закладки в облачное хранилище -> Закладки в облако
Сохранить закладку (последнее выделение) -> Сохранить закладку
Сохранить книгу на Яндекс.Диск -> Книгу на Я.Диск
Сохранить настройки на облачное хранилище -> Настройки в облако
Сохранить позицию чтения в облачное хранилище -> Позицию в облако
Экспериментальная функция -> Экспериментальное
Яркость подсветки установленная в системе -> Системная яркость

**Comment by plotn** [comment]
@kaznelson, я ж делал это? Проверил диалог яркости, там сейчас короткий текст

**Comment by kaznelson** [comment]
Дико извиняюсь. Проверил - имена короткие.
Просто это мимо меня как-то тихо прошло. А сейчас в отпуске, вот и...
