### ISSUE TITLE
UX - диалог выбора цвета шрифта

### ISSUE THREAD

**Issue by kartun83** [plotn/coolreader#695]
- диалог выбора цвета шрифта сильно отличается от диалога выбора цвета фона.
- в данном контексте плохо понятно что значит "-", возможно стоит поменять текст на "не изменять"
- список цветов существенно меньше чем в выборе фонов
- нет возможности добавить произвольный цвет (крутилками или вручную)
- нет preview - как текст будет выглядеть с учётом остальных настроек
- control ввода текста визуально отличается от того, который используется в выборе цвета фона
- hint в контроле ввода неинформативен

![Screenshot_20230414-062548_KnownReader premium](https://user-images.githubusercontent.com/5894573/232012084-ac500d56-b1e5-4fb7-bd45-de6d4c4fed81.png)

![Screenshot_20230414-060016_KnownReader premium](https://user-images.githubusercontent.com/5894573/232011996-e1f0eaf1-629a-4b17-b0a1-fed1a8956186.png)

**Comment by plotn** [comment]
Если не возражаешь, я закрою тикет. Тут суть в том , что это разные диалоги - он связан со свойствами цсс в книгах, другой - чисто уже в самом интерфейсе
