### ISSUE TITLE
apikey.properties

### ISSUE THREAD

**Issue by kartun83** [plotn/coolreader#696]
при клонировании репозитория и открытии в android studio gradle ломается из-за отсуствия файла rootProject.file("apikey.properties"). В доках это никак не отражено.
![Screenshot from 2023-04-14 14-38-23](https://user-images.githubusercontent.com/5894573/232034663-b88b1b2a-bc5f-4ea4-964e-c1a878b6eb7e.png)

**Comment by plotn** [comment]
добавил файл для примера:
apikey.properties.example

Переименуй в апикей.пропертис и попробуй
